"""Convert data/Data_Master_IRN_FWCI_ITS.xlsx into data/dataset.json and data/dataset.js.

Dev-time only script - not used at runtime by the browser. Re-run this whenever
the source spreadsheet changes, then commit the regenerated dataset.json/dataset.js.

Usage:
    python scripts/convert_xlsx_to_json.py [path/to/workbook.xlsx] [output/dir]

Defaults to data/Data_Master_IRN_FWCI_ITS.xlsx -> data/
"""
import json
import re
import sys
from pathlib import Path

import openpyxl

SKIP_SHEETS = {"Panduan", "Topik_Unggulan_Fakultas"}

SHEET_KEY_MAP = {
    "Fakultas": "fakultas",
    "Departemen": "departemen",
    "Dosen": "dosen",
    "Institusi_Mitra": "institusiMitra",
    "Publikasi": "publikasi",
    "Publikasi_Penulis": "publikasiPenulis",
    "Naskah_Pipeline": "naskahPipeline",
    "Universitas_Pembanding": "universitasPembanding",
    "Universitas_Pembanding_FWCI": "universitasPembandingFwci",
    "Metrik_ITS_Tahunan": "metrikItsTahunan",
    "Kolaborasi_Pembanding": "kolaborasiPembanding",
}

HELPER_HEADER_RE = re.compile(r"\((helper|formula)\)", re.IGNORECASE)


def is_helper_column(header):
    return bool(header) and bool(HELPER_HEADER_RE.search(str(header)))


def sheet_to_rows(ws):
    rows_iter = ws.iter_rows(values_only=True)
    headers = next(rows_iter, None)
    if headers is None:
        return []
    keep_idx = [i for i, h in enumerate(headers) if h is not None and not is_helper_column(h)]
    kept_headers = [str(headers[i]).strip() for i in keep_idx]

    out = []
    for row in rows_iter:
        if all(v is None for v in row):
            continue
        record = {}
        for i, header in zip(keep_idx, kept_headers):
            value = row[i] if i < len(row) else None
            record[header] = value
        out.append(record)
    return out


def convert(xlsx_path: Path, out_dir: Path):
    wb = openpyxl.load_workbook(xlsx_path, data_only=True)
    dataset = {}
    for sheet_name in wb.sheetnames:
        if sheet_name in SKIP_SHEETS:
            continue
        key = SHEET_KEY_MAP.get(sheet_name)
        if key is None:
            print(f"  warn: sheet '{sheet_name}' tidak dikenal, dilewati", file=sys.stderr)
            continue
        dataset[key] = sheet_to_rows(wb[sheet_name])
        print(f"  {sheet_name} -> {key}: {len(dataset[key])} baris")

    missing = [k for k in SHEET_KEY_MAP.values() if k not in dataset]
    if missing:
        print(f"  warn: sheet berikut tidak ditemukan di workbook: {missing}", file=sys.stderr)

    out_dir.mkdir(parents=True, exist_ok=True)
    json_path = out_dir / "dataset.json"
    js_path = out_dir / "dataset.js"

    json_text = json.dumps(dataset, ensure_ascii=False, indent=2, default=str)
    json_path.write_text(json_text, encoding="utf-8")
    js_path.write_text(
        "// Auto-generated by scripts/convert_xlsx_to_json.py - jangan edit manual.\n"
        "window.__DASHBOARD_DATA__ = " + json_text + ";\n",
        encoding="utf-8",
    )
    print(f"Selesai: {json_path} dan {js_path}")


if __name__ == "__main__":
    root = Path(__file__).resolve().parent.parent
    xlsx_arg = Path(sys.argv[1]) if len(sys.argv) > 1 else root / "data" / "Data_Master_IRN_FWCI_ITS.xlsx"
    out_arg = Path(sys.argv[2]) if len(sys.argv) > 2 else root / "data"
    print(f"Membaca {xlsx_arg} ...")
    convert(xlsx_arg, out_arg)
